public class Main {
    public static void main(String[] args) {
        System.out.println("Hello world!");
   var dog = 8.0;
   var cat = 3.6;
   var paper = 763789;
        System.out.println(dog);
        System.out.println(cat);
        System.out.println(paper);
        dog = dog + 4;
        cat = cat + 4;
        paper = paper +4;
        System.out.println(dog);
        System.out.println(cat);
        System.out.println(paper);
        dog = dog - 3.5;
        cat = cat - 1.6;
        paper = paper - 7639;
        System.out.println(dog);
        System.out.println(cat);
        System.out.println(paper);
        var friend = 19;
        System.out.println(friend);
        friend = friend + 2;
        System.out.println(friend);
        friend = friend / 7;
        System.out.println(friend);
        var frog = 3.5;
        System.out.println(frog);
        frog = frog * 10;
        System.out.println(frog);
        frog = frog / 3.5;
        System.out.println(frog);
        frog = frog + 4;
        System.out.println(frog);
        var weightFirstBoxer = 78.2;
        var weightSecondBoxer = 82.7;
        var weightTwoBoxers = weightFirstBoxer + weightSecondBoxer;
        System.out.println("Общая масса составляет " +weightTwoBoxers + " кг.");
        var weightDifference = weightSecondBoxer - weightFirstBoxer;
        System.out.println("Разница в весе " +weightDifference + " кг.");
        var divisionWeight = weightSecondBoxer % weightFirstBoxer;
         System.out.println(divisionWeight + " кг.");
         var totalHours = 640;
         var hoursPerEmployee = 8;
         var employeesInCompany = totalHours / hoursPerEmployee;
         System.out.println("Всего работников в компани - " + employeesInCompany + " человек");
         employeesInCompany = employeesInCompany + 94;
         totalHours = employeesInCompany * hoursPerEmployee;
         System.out.println("Если в компании работает " +employeesInCompany + " человек, то всего " + totalHours + " часов работы может быть поделено между сотрудниками");
    }
}